[package]
name = "touchbar-sessiond"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
glow.workspace = true
khronos-egl.workspace = true
libc.workspace = true
memmap2.workspace = true
tempfile.workspace = true
toml.workspace = true
touchbar-control = { path = "../touchbar-control" }
touchbar-broker-schema = { path = "../touchbar-broker-schema" }
touchbar-protocol = { path = "../touchbar-protocol" }
touchbar-package = { path = "../touchbar-package" }
touchbar-plugin-store = { path = "../touchbar-plugin-store" }
touchbar-policy = { path = "../touchbar-policy" }
touchbar-profile-config = { path = "../touchbar-profile-config" }
touchbar-layout = { path = "../touchbar-layout" }
touchbar-model = { path = "../touchbar-model" }
touchbar-system-bar = { path = "../touchbar-system-bar" }
touchbar-ui = { path = "../touchbar-ui" }
wayland-client.workspace = true
wayland-protocols.workspace = true
wayland-server.workspace = true
