[package]
name = "touchbar-protocol"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
libc.workspace = true
touchbar-layout = { path = "../touchbar-layout" }
wayland-backend.workspace = true
wayland-client.workspace = true
wayland-scanner.workspace = true
wayland-server.workspace = true
